name: Dockle CI Scan

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *' # every day at 15:00 UTC (8:00 AM Pacific)

jobs:
  dockle:
    name: docker-scan-dockle
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          docker build . -t us.gcr.io/recidiviz-staging/appengine/default:latest
      - name: Run Dockle
          uses: erzz/dockle-action@v1
          with:
            image: 'us.gcr.io/recidiviz-staging/appengine/default:latest'
            report-format: sarif
            report-name: dockle-report
        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v2
          with:
            # Path to SARIF file relative to the root of the repository
            sarif_file: dockle-report.sarif
